### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt'

### ISSUE THREAD

**Issue by thainq107** [MarceloSancinetti/epa-gop-pykaldi#3]
When I run dataprep.py:
!python run_dataprep.py --config configs/dataprep.yaml

I get an error:
FileNotFoundError: [Errno 2] No such file or directory: 'librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt'
This file is not included in the downloaded pre-training model?
How can I get this file, or can you send me this file?
Thanks!

**Comment by LijingDK** [comment]
当我运行 dataprep.py 时：
!python run_dataprep.py --config configs/dataprep.yaml

我得到一个错误：
FileNotFoundError: [Errno 2] No such file or directory: 'librispeech_models/exp/chain_cleaned/tdnn_1d_sp/final.txt'
这个文件没有包含在下载的预训练模型中？
我怎样才能得到这个文件，或者你能把这个文件发给我吗？
谢谢！
我的问题是和上面的同学一样的，我们没法得到这个final.txt文件，您可以将这个分享给我们么？不然我们无法复现这份您共享的代码，非常感谢您
